/*
Copyright 2024 The ORC Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// FloatingIPResourceStatusApplyConfiguration represents a declarative configuration of the FloatingIPResourceStatus type for use
// with apply.
type FloatingIPResourceStatusApplyConfiguration struct {
	Description       *string  `json:"description,omitempty"`
	ProjectID         *string  `json:"projectID,omitempty"`
	ExternalNetworkID *string  `json:"externalNetworkID,omitempty"`
	Status            *string  `json:"status,omitempty"`
	Tags              []string `json:"tags,omitempty"`
}

// FloatingIPResourceStatusApplyConfiguration constructs a declarative configuration of the FloatingIPResourceStatus type for use with
// apply.
func FloatingIPResourceStatus() *FloatingIPResourceStatusApplyConfiguration {
	return &FloatingIPResourceStatusApplyConfiguration{}
}

// WithDescription sets the Description field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Description field is set to the value of the last call.
func (b *FloatingIPResourceStatusApplyConfiguration) WithDescription(value string) *FloatingIPResourceStatusApplyConfiguration {
	b.Description = &value
	return b
}

// WithProjectID sets the ProjectID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ProjectID field is set to the value of the last call.
func (b *FloatingIPResourceStatusApplyConfiguration) WithProjectID(value string) *FloatingIPResourceStatusApplyConfiguration {
	b.ProjectID = &value
	return b
}

// WithExternalNetworkID sets the ExternalNetworkID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ExternalNetworkID field is set to the value of the last call.
func (b *FloatingIPResourceStatusApplyConfiguration) WithExternalNetworkID(value string) *FloatingIPResourceStatusApplyConfiguration {
	b.ExternalNetworkID = &value
	return b
}

// WithStatus sets the Status field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Status field is set to the value of the last call.
func (b *FloatingIPResourceStatusApplyConfiguration) WithStatus(value string) *FloatingIPResourceStatusApplyConfiguration {
	b.Status = &value
	return b
}

// WithTags adds the given value to the Tags field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Tags field.
func (b *FloatingIPResourceStatusApplyConfiguration) WithTags(values ...string) *FloatingIPResourceStatusApplyConfiguration {
	for i := range values {
		b.Tags = append(b.Tags, values[i])
	}
	return b
}
